source 'https://www.rubygems.org'

gem 'json', '~> 1.7.7'
gem 'sinatra'
gem 'rake'
gem 'thin'
gem 'unicorn'
gem 'rack-contrib'
gem 'haml'
gem 'google-api-client'
gem 'activesupport'
gem 'pry'
gem 'tzinfo'
